# Generated by Django 3.0.5 on 2020-06-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeongsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, 2021)], verbose_name='학년도')),
                ('gun', models.CharField(choices=[('GA', '가군'), ('NA', '나군'), ('DA', '다군'), ('ETC', '군외')], max_length=7, verbose_name='군')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeongsis', to='university.University', verbose_name='대학')),
            ],
            options={
                'verbose_name': '정시전형',
                'verbose_name_plural': '정시전형',
            },
        ),
        migrations.CreateModel(
            name='JeongsiSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='설명')),
                ('start_date', models.DateTimeField(verbose_name='시작시간')),
                ('end_date', models.DateTimeField(verbose_name='종료시간')),
                ('jeongsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeongsi_schedules', to='jeongsi.Jeongsi', verbose_name='정시전형 종류')),
                ('major_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeongsi_schedules', to='university.JeongsiMajorBlock', verbose_name='학과 블록')),
            ],
            options={
                'verbose_name': '정시전형 일정',
                'verbose_name_plural': '정시전형 일정',
            },
        ),
    ]
