# Generated by Django 3.0.7 on 2020-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='susischedule',
            name='block',
            field=models.CharField(default='', editable=False, max_length=63),
        ),
        migrations.AddField(
            model_name='susischedule',
            name='jh',
            field=models.CharField(default='', editable=False, max_length=63),
        ),
        migrations.AddField(
            model_name='susischedule',
            name='sj',
            field=models.CharField(default='수시', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='susischedule',
            name='university',
            field=models.CharField(default='', editable=False, max_length=31),
        ),
    ]
