# Generated by Django 3.0.5 on 2020-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='susischedule',
            name='susi_detail',
        ),
        migrations.AddField(
            model_name='susischedule',
            name='susi_detail',
            field=models.ManyToManyField(to='susi.SusiDetail', verbose_name='수시전형 종류'),
        ),
    ]
