# Generated by Django 2.2.11 on 2020-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
