# Generated by Django 3.0.5 on 2020-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=20, unique=True, verbose_name='대학명')),
                ('url', models.CharField(max_length=50, verbose_name='리뷰 url')),
            ],
            options={
                'verbose_name': '대학 리뷰',
                'verbose_name_plural': '대학 리뷰',
            },
        ),
    ]
