# Generated by Django 3.0.5 on 2020-06-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True, verbose_name='대학명')),
                ('logo', models.CharField(blank=True, max_length=31, verbose_name='대학 로고')),
            ],
            options={
                'verbose_name': '대학',
                'verbose_name_plural': '대학',
            },
        ),
        migrations.CreateModel(
            name='SusiMajorBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='분류명')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susi_major_blocks', to='university.University', verbose_name='소속 대학')),
            ],
            options={
                'verbose_name': '수시 학과 블록',
                'verbose_name_plural': '수시 학과 블록',
            },
        ),
        migrations.CreateModel(
            name='JeongsiMajorBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='분류명')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeongsi_major_blocks', to='university.University', verbose_name='소속 대학')),
            ],
            options={
                'verbose_name': '정시 학과 블록',
                'verbose_name_plural': '정시 학과 블록',
            },
        ),
    ]
